jamiebrynes7/spatialos-sdk-rs

- spatialos-sdk/examples/project-example/main.rs
- spatialos-sdk/src/worker/core/connection.rs
- spatialos-sdk/src/worker/core/parameters.rs
This allows for a more idiomatic, clean way of declaring connection parameters.
> Add Builder Pattern to Connection Parameters

- spatialos-sdk/Cargo.toml
- spatialos-sdk/examples/project-example/Cargo.toml
- spatialos-sdk/examples/project-example/lib/connection_handler.rs
- spatialos-sdk/src/worker/connection.rs
- spatialos-sdk/src/worker/locator.rs
Porting over the connection and deployment list futures over to use the `futures` crate.
TODO:
> Use futures crate for wrapping futures in WorkerSDK

- spatialos-sdk-sys/build.rs
- spatialos-sdk-tools/Cargo.toml
Found a bug where if you actually build using Windows (instead of WSL, whoops) the pathing was broken for finding the libraries.
> Update dependencies + fix Window build

- spatialos-sdk/src/worker/mod.rs
The derived implementation of `PartialEq` for `RequestId<T>` required that `T: PartialEq`, which means that you couldn't directly compare request IDs for most request types. Fortunately, we don't actually need that trait bound since the only thing we're comparing is `id`, so we can manually implement `PartialEq` in order to directly compare two `RequestId` objects.
On a related note, I've also made `RequestId::id` private, since we no longer need to access it directly in order to compare `RequestId`s. This improves encapsulation, and has the added advantage making `RequestId` more type-safe, since you can now only compare two `RequestId`s if they have the same type parameter (i.e. you can't compare a `RequestId<Foo>` and a `RequestId<Bar>`).
> Implement PartialEq for RequestId and make id private

- LICENSE-APACHE
- LICENSE-MIT
- README.md
Add dual MIT/Apache 2.0 license - standard practice for Rust crates.
Fixes #40
> Add Dual License

- spatialos-sdk/Cargo.toml
- spatialos-sdk/src/worker/mod.rs
`RequestId<T>` wasn't being marked as `Send` or `Sync` because of the `PhantomData<*const T>` marker. I've manually implemented them, and left a comment explaining why the impls are safe.
I also removed `RequestId::to_string`, which seemed like an unnecessary helper function that's not being used? If there's a use case that's not covered by the `Debug` impl for `RequestId`, then let me know and we can figure out a more idiomatic solution 🙂 
---
UPDATE: I realized that this issue applies to all of the traits being derived for `RequestId`. Rather than manually implementing all the traits myself, I've pulled in the [derivative](https://mcarton.github.io/rust-derivative/) crate, which provides more configurable versions of the built in trait derives, including the ability to manually specify …
> Custom derive traits for RequestId

- spatialos-sdk/examples/project-example/main.rs
- spatialos-sdk/src/lib.rs
- spatialos-sdk/src/ptr.rs
- spatialos-sdk/src/worker/connection.rs
Based on what [Alastair said on the forums](https://forums.improbable.io/t/thread-safety-of-worker-connection-object/5358/2?u=randompoison), the worker connection should be safe to share between threads if wrapped in a mutex. For our purposes, that means that `WorkerConnection` is already `Send`, which is all we need to wrap it in a `Mutex` and start sharing it between threads. Fortunately, with some minor adjustments, `WorkerConnection` can also be made `Sync`, which enables a wider variety threading models for managing the connection.
So long as we always access the underlying `*mut Worker_Connection` pointer through `&mut self`, Rust's ownership system will guarantee that only one thread has access to the connection at a time. So all we should need in order to safely implement `Sync` …
> Make WorkerConnection Send/Sync

- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/examples/project-example/generated_code.rs
- spatialos-sdk/src/worker/commands.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/connection.rs
- spatialos-sdk/src/worker/parameters.rs
* Implement `send_command_request`, `send_command_response`, and `send_command_error` on `WorkerConnection`.
* Have `send_command_error` return a `Result<(), NulError>` in case the user passes in a message that can't be safely converted to a C string.
* Remove `CommandParameters`, opting to pass the `allow_short_circuit` option directly to `send_command_request`.
> Implement command request/response methods

- .travis.yml
The Rust 1.33 release means the 1.34 beta is live and..
Looks like the beta version of 1.34 has some breaking changes in Clippy which perscribe: 
```
error: redundant closure found
--> spatialos-sdk/src/worker/connection.rs:484:18
|
484 |             .map(|x| x.to_worker_sdk())
|                  ^^^^^^^^^^^^^^^^^^^^^ help: remove closure as shown: `worker::InterestOverride::to_worker_sdk`
|
= note: `-D clippy::redundant-closure` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
error: redundant closure found
--> spatialos-sdk/src/worker/query.rs:252:26
|
252 |                     .map(|x| x.constraint_len_recursive())
|                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove closure as …
```
> Rust 1.34 breaking changes

- project-example/Cargo.toml
- project-example/rust_client.json
- project-example/src/connection_handler.rs
- project-example/src/main.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/Cargo.toml
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/parameters.rs
This PR introduces the use of the inventory crate for automatic component registration. 
- Added `WrappedVTable` as you must own the type that you call `inventory::collect!()` on. 
- Could look into whether a typedef is sufficient for this.
- Driveby fix on the worker configs (FPL changes) 
Fixes #57 
Fixes #71 (most of the work appeared to have been done for this..?)
> Use inventory for automatic component registration 

- project-example/src/main.rs
- spatialos-sdk/src/worker/op.rs
Reworked the `ReservedEntityIdsRange` to be an iterator and hid the internals. 
Fixes #65
> Make ReserveEntityIdsResponse contain an iterator

- spatialos-sdk/src/worker/metrics.rs
Fixed a bug where load was reported as 0 always due to taking a reference to a local variable.
> Fix Load Metric

- project-example/src/main.rs
- spatialos-sdk/src/worker/entity.rs
- spatialos-sdk/src/worker/entity_builder.rs
- spatialos-sdk/src/worker/mod.rs
- test-suite/src/entity_builder_tests.rs
- test-suite/src/lib.rs
- test-suite/src/snapshot_integration_tests.rs
This PR introduces an `EntityBuilder` which helps users create entities and cuts down the verbosity required to do so.
It includes: 
- Forcing a user to provide a position (required component).
- Automatic building of the `EntityACL` component (required component).
- Making users specify a write-access layer when adding a component.
- Providing special methods for other well-known components (Metadata and Persistence).
These four features makes it much less error-prone when creating entities. However, there is still one place to trip up on:
- Setting read layers is still done in a separate method. This is easy to mess up (by omission). We could make this part of the EntityBuilder constructor to force users to pass this in, but the constructor will start to get very long.
Note that there …
> Add Entity Builder

- spatialos-sdk/src/worker/connection.rs
Noticed a memory leak when sending updates when implementing a view and tracked it down to this.
TL;DR - the C API will call the vtable copy function, but won't free the original data. We need to free the data after calling the C API function.
> Fix memory leak

- spatialos-sdk-code-generator/src/generator.rs
Hit this one as well - the import was slightly wrong for `EntityId` in generated code.
> Entity id codegen bugfix

- spatialos-sdk/src/worker/snapshot.rs
- test-suite/src/snapshot_integration_tests.rs
Missed this one in the original PR :grimacing:
> Make SnapshotOutputStream::write_entity a mutable borrow

- project-example/.gitignore
- project-example/src/generated.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk-code-generator/src/generator.rs
Noticed that enums weren't fully implemented in the code generation side. We now generate the elements of the enum along with a `From<u32>` impl to help with the deserialization side.
> Implement enums in code generation

- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/schema/component_update.rs
- spatialos-sdk/tests/manual_serialization.rs
Since component events and fields can't have the same name, we can add events directly to the generated component update type, which makes implementing events pretty trivial 😁
> Add events to component updates (serialization rewrite)

- spatialos-sdk/src/worker/connection.rs
- spatialos-sdk/src/worker/parameters.rs
Sketch out an alternate approach to converting a `ConnectionParameters` to a `Worker_ConnectionParameters`, specifically using a different strategy for populating the various pointers hiding in `Worker_Alpha_ModularUdpNetworkParameters `.
This approach uses a new enum `IntermediateProtocolType` to "flatten" the contents of `ProtocolType::Udp` into the corresponding C structs on the stack. From there, we can populate the final `Worker_ConnectionParameters` from the values on the stack.
From a safety perspective, this is functionally equivalent to the closure-based approach implemented in #105, which is to say that it's *mostly* safe but can't completely statically prevent misuse due to the nature of FFI and using C structs. I'd personally argue that the intermediate struct approach is a …
> WIP: Alternate ConnectionParameters to Worker_ConnectionParameters conversion

- project-example/src/generated.rs
Also, how do you feel about checking in the files, generally?
Against checking-in, on principle version control systems really only ought to track human-generated content.
However, the idiosyncrasies of a build system sometimes lend to more convenience. For example, my workflow (VScode + RLS) fails on a clean checkout if I haven't run the cargo spatial codegen command. I'm not sure if this would work differently if the generated code were managed by a build.rs script. What good looks like, in my opinion, is [Pants Java Protobuf](https://www.pantsbuild.org/build_dictionary.html#bdict_java_protobuf_library) which seamlessly links generated code to your classpath (and IDE) without requiring the generated code to be checked-in.
> Checking in latest codegen

- cargo-spatial/Cargo.toml
- cargo-spatial/src/download.rs
- cargo-spatial/src/opt.rs
Somewhere in the `13.x` releases, a new package was published which contains exhaustive test schema. This test schema is meant to test code generators and ensure they can generate valid code for the schema spec.
In preparation for actually doing this testing, this PR adds an optional flag to `cargo spatial download sdk` that will download the test schema into: 
```
sdk_dir/test-schema
```
> Add option to download test schema

- .github/workflows/premerge.yml
- Spatial.toml
- cargo-spatial/src/config.rs
I'm planning to drop support for Travis CI and replace it with GitHub Actions due to:
- Code reusability for components of CI.
- Better GitHub integration (annotations, etc.)
- Better Windows support
This PR introduces a GitHub Actions pipeline that should act as a pre-merge check. It replicates the current Travis CI behaviour. As a bonus, it runs noticeably faster!
> Use Github actions 

- spatialos-sdk/src/worker/commands.rs
- spatialos-sdk/src/worker/component.rs
One note I had when writing user code is that manually cloning the parameters everywhere is really annoying. 
Given they are small structs and are likely to remain so in the future, this feels like a safe thing to do.
Also driveby updated a docs link
> Add `Copy` to `UpdateParameters` and `CommandParameters`

- .github/workflows/premerge.yml
- cargo-spatial/Cargo.toml
- cargo-spatial/src/codegen.rs
- cargo-spatial/src/config.rs
- cargo-spatial/src/lib.rs
- cargo-spatial/src/local.rs
- project-example/Spatial.toml
In `cargo-spatial` we assumed that there would be a `schema` directory next to the `Spatial.toml`. This may not be true, as is the case with our `test-suite` crate.
This PR removes the default assumption of this `schema` directory and removes some unused/low-impact dependencies for the `cargo-spatial` tool.
> Allow users not to have a `schema` directory 

- .github/workflows/premerge.yml
- project-example/spatialos.json
> Duped from #118 such that CI can run 
This fixes the following bug when running `cargo spatial local launch`
```
Encountered an error during command execution.                                 Snapshot file is not set. Please provide a snapshot file using either t
he --snapshot flag or the 'defaultSnapshotUploadFilepath' field under 'snapshot' in the project configuration file
```
Could be that there's an alternative approach, but this felt easy enough.
> add default snapshot to project config

- .github/workflows/premerge.yml
Install `cargo spatial` in debug mode. Sacrifices `cargo spatial` execution time for compile time.
> Small speed up to CI

- spatialos-sdk/Cargo.toml
- spatialos-sdk/src/worker/entity_builder.rs
- spatialos-sdk/src/worker/schema/command_request.rs
- spatialos-sdk/src/worker/schema/command_response.rs
- spatialos-sdk/src/worker/schema/component_data.rs
- spatialos-sdk/src/worker/schema/component_update.rs
- spatialos-sdk/src/worker/schema/object.rs
- spatialos-sdk/src/worker/schema/primitives.rs
This is the first of the schema data object soundness fixes. It follows the pattern described in #101 to make the schema data types sound. In summary:
* Make `SchemaObject` an opaque type that is never actually instantiated.
* Cast and dereference a `*mut Schema_Object` to either a `&SchemaObject` or a `&mut SchemaObject`, depending on what is valid for the context.
* Internally within the SDK, convert a `&SchemaObject` or `&mut SchemaObject` back to a `*mut Schema_Object` to pass into the C API.
This provides an idiomatic Rust API that allows us to correctly track lifetimes and enforce mutability constraints.
---
For the most part, this required very little change to the internals of the SDK or public API, and no changes to code generation. We were already passing …
> Fix soundness holes in SchemaObject

- project-example/src/generated.rs
- project-example/src/main.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/entity.rs
- spatialos-sdk/src/worker/entity_builder.rs
- spatialos-sdk/src/worker/op.rs
- spatialos-sdk/src/worker/schema.rs
- spatialos-sdk/src/worker/schema/component_data.rs
- spatialos-sdk/src/worker/schema/owned.rs
Further work re-implementing the work from #101, this time patching up the soundness holes in `SchemaComponentData`. This is very similar to the changes in #127, with the addition step of adding the `Owned` smart pointer type.
`Owned` is like `Box`, but used only for the schema data objects. This abstraction is necessary because even when we "own" a `Schema_ComponentData`, we only have a pointer and not the struct itself. As such, we can't represent it in Rust as a struct on its own or the ownership interactions will (to use a technical term) get all fucky. In this case, we need to create our own smart pointer type instead of using `Box` directly since each schema data object objects has its own deallocation function in the C API.
As a helper for `Owned`, we also define …
> SchemaComponentData soundness

- project-example/src/generated.rs
- project-example/src/main.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/op.rs
- spatialos-sdk/src/worker/schema/command_request.rs
- spatialos-sdk/src/worker/schema/command_response.rs
- spatialos-sdk/src/worker/schema/component_update.rs
Fix soundness holes for remaining schema data objects (`SchemaComponentUpdate`, `SchemaCommandRequest`, and `SchemaCommandResponse`). This follows the same pattern as described in #101. I've also grouped up the remaining three because at this point all the changes are the same as the ones done in #127 and #128, it's just a lot of boilerplate changes at this point.
> Remaining soundness fixes

- spatialos-sdk/src/worker/entity.rs
- spatialos-sdk/src/worker/schema.rs
- spatialos-sdk/src/worker/schema/command_request.rs
- spatialos-sdk/src/worker/schema/command_response.rs
- spatialos-sdk/src/worker/schema/component_data.rs
- spatialos-sdk/src/worker/schema/component_update.rs
- spatialos-sdk/src/worker/schema/macros.rs
- spatialos-sdk/src/worker/schema/object.rs
- spatialos-sdk/src/worker/schema/owned.rs
- spatialos-sdk/src/worker/schema/primitives.rs
- spatialos-sdk/src/worker/schema/ptr.rs
> Part of #121
This PR is a cleanup pass after the previous work done to fix the soundness holes in the schema data object types (#127, #128, and #129).
I've added the `DataPointer` trait to unify the functionality for handling the schema data objects. It provides default functions for converting between Rust references and the raw pointer representation, removing the need to have that logic duplicated for each type. I've also added documentation around the invariants that must be maintained in order to for the implementation to be safe.
Per @jamiebrynes7's suggestion, I've changed `as_ptr` to return a `*const Self::Raw` and added a separate `as_ptr_mut` method. In the cases where a method taking `&self` calls a C function that needs `*mut T`, we manually cast the pointer types. The …
> Unify handling of data pointer types

- project-example/src/generated.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk-code-generator/src/generator.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/op.rs
- spatialos-sdk/src/worker/schema.rs
- spatialos-sdk/src/worker/schema/collections.rs
- spatialos-sdk/src/worker/schema/component_data.rs
- spatialos-sdk/src/worker/schema/object.rs
- spatialos-sdk/src/worker/schema/primitives.rs
This PR unifies how schema data serialization is handled, specifically allowing collection types and user-defined types (struct types and enums) to be serialized via the same mechanism as primitive types. This allows us to drastically simplify the serialization code generated for schema-defined types.
* Rename `SchemaPrimitiveField` to `Field` now that it is used for all field types and not just primitives.
* Remove `component::TypeConversion` trait and replace it with `schema::ObjectField` trait. This trait functions largely the same as before, but function names have been changed and functions no longer return `Result`s.
* Add a blanket impl of `Field` for all types implementing `ObjectField`. This ensures we only have to generate code for the simpler `ObjectField` …
> Unify serialization logic

- project-example/src/generated.rs
- project-example/src/main.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk-code-generator/src/generator.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/op.rs
- spatialos-sdk/src/worker/schema.rs
- spatialos-sdk/src/worker/schema/collections.rs
- spatialos-sdk/src/worker/schema/component_update.rs
- spatialos-sdk/src/worker/schema/primitives.rs
This PR improves serialization of component updates by integrating them directly into the main serialization logic.
* Add `has_update`, `get_update`, and `add_update` methods to the `Field` trait. This allows collection types to smoothly handle cleared fields without needing special-case handling in the code generator.
* Remove `from_update` and `to_update` methods from `Component` and move them into a separate `Update` trait.
* Add `field_cleared` and `add_cleared` methods to `SchemaComponentUpdate`.
* Remove the `ComponentData` and `UpdateData` traits, merging (heh) their functionality into `Component` and `Update`.
* Add `from_update` and `deserialize` helpers to `SchemaComponentUpdate`.
> Improve update serialization

- cargo-spatial/src/codegen.rs
- spatialos-sdk-code-generator/src/schema_bundle.rs
While looking at add automated testing against the exhaustive test schema, I ran into issues where schema bundles that failed to be parsed would not give the underlying error. 
To resolve this, I've added more robust error handling in the codegen command so we no longer swallow the underlying errors. No fancy error handling crates, just using the std library (for now anyway, given how much they seem to churn).
I'll probably go over the rest of `cargo-spatial` and clean up error handling if we are happy with this pattern. An example error looks like: 
```
jamie /c/Workspace/spatialos-sdk-rs/test-suite (feature/exhaustive-test-schema) 
λ cargo spatial codegen
Error: CodegenError { kind: InvalidBundle, msg: "Failed to parse contents of bundle.json", inner: Some(Error("invalid type: string …
```
> Better error handling in codegen

- .github/workflows/premerge.yml
- README.md
- project-example/Cargo.toml
- project-example/src/connection_handler.rs
- project-example/src/main.rs
- project-example/src/opt.rs
- spatialos-sdk/Cargo.toml
- spatialos-sdk/src/worker/connection.rs
- spatialos-sdk/src/worker/internal/mod.rs
- spatialos-sdk/src/worker/locator.rs
- spatialos-sdk/src/worker/metrics.rs
- spatialos-sdk/src/worker/mod.rs
- spatialos-sdk/src/worker/op.rs
- spatialos-sdk/src/worker/snapshot.rs
- spatialos-sdk/src/worker/utils.rs
- spatialos-sdk/src/worker/worker_future.rs
This PR is a grab bag of things: 
- Use the standard library `Future` trait for the Worker SDK futures! Move to using async-await with the worker SDK futures. 
- Remove the `internal` module and move `utils` up one module.
- Refactoring the connection error handling structs
- All the connection methods consume the `ConnectionParameters` struct rather than borrow it.
If people wish, I can attempt to split these into multiple PRs
> Upgrade to Rust 1.39 + use new futures

- cargo-spatial/src/codegen.rs
- cargo-spatial/src/config.rs
- cargo-spatial/src/download.rs
- cargo-spatial/src/errors.rs
- cargo-spatial/src/lib.rs
- cargo-spatial/src/local.rs
Following on from #139, this PR implements the same approach for the rest of the commands. In doing so, we generalise the error struct into its own module.
> `cargo-spatial` error handling consolidation

- spatialos-sdk-sys/Cargo.toml
- spatialos-sdk-sys/build.rs
- spatialos-sdk/Cargo.toml
- The `lazy_static` dependency in `spatialos-sdk` was unused.
- The `lazy_static` build dependency in `spatialos-sdk-sys` was not necessary.
> Remove some lazy_static dependencies

- project-example/schema/example.schema
- project-example/src/generated.rs
- project-example/src/main.rs
- spatialos-sdk-code-generator/src/generator.rs
- spatialos-sdk/src/worker/entity.rs
- spatialos-sdk/src/worker/schema.rs
- spatialos-sdk/src/worker/schema/object.rs
- spatialos-sdk/src/worker/schema/primitives.rs
This PR adds the schema `entity` type. This corresponds to the `worker::entity::Entity` struct in Rust.
This schema type is structured like:
```
entity field
field id 54 --> SchemaObject (position_component)
field id 100 -> SchemaObject (some_component)
...
```
such that a component is de/serialized from/to the field ID that corresponds to that component ID. We expose two new methods in the `VTable` struct to accommodate this structure which allow us to (de)serialize directly to/from the `SchemaObject`.
---
This PR also has a assorted set of changes to support this schema type.
- The `Component` trait requires `Clone` such that we can deep copy the `Entity` object. (The worker vtable "copy" is only a shallow copy). 
- Some convenience methods for mutating the `Entity` object.
- Exposing …
> Add schema `Entity` type

- spatialos-sdk/src/worker/connection.rs
- spatialos-sdk/src/worker/mod.rs
- spatialos-sdk/src/worker/op.rs
We used to do this in the C# SDK as well and its not really very helpful. 
Imagine you wanted to store a list of pending requests, you end up needing to type-erase the generic type in them. (I came across this when trying to build a demo and ended up falling back to the inner id)
It also makes the implementation a bit simpler.
> Remove generic type from `RequestId`

- project-example/src/main.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/connection.rs
This PR introduces an intermediate abstraction for sending component updates that the `Connection` trait understands. 
The rationale for adding this abstraction is to allow manually created update objects to be sent along with generated update structs:
```rust
let schema_update = SchemaComponentUpdate::new();
let update = ComponentUpdate { schema_data: schema_update, component_id: 54 };
connection.send_component_update(EntityId(5), update, UpdateParams{});
let generated_update = PositionUpdate::default();
connection.send_component_update(EntityId(5), update, UpdateParams{});
```
We can add a similar pattern to commands when the traits for those are finished 😄. This would decouple the `Connection` trait from the `Component`/`Update`/`CommandRequest/Response` traits (and thus generated …
> Flexible component update sending

- project-example/schema/example.schema
- project-example/src/generated.rs
- spatialos-sdk-code-generator/src/generator.rs
- spatialos-sdk/src/worker/schema/collections.rs
This PR introduces recursive schema option support. This is an edge case in schemalang where the following is valid schema.
```
type Recursive {
option<Recursive> opt = 1;
}
type TypeA {
option<TypeB> opt = 1;
}
type TypeB {
option<TypeA> opt = 1;
}
```
To support this edge case, we detect when a field is recursive (i.e. - cyclical) and change the type from `Option<T>` to `Option<Box<T>>`. 
To enable this, we add another schema container `RecursiveOptional<T>` which is almost identical to `Optional<T>` except it has an additional trait bound `ObjectField` since only types can be optional _and_ the `RustType` alias has the additional `Box`. 
---
For the above schema this change should now generate:
```rust
struct Recursive {
pub opt: Option<Box<Recursive>>
}
struct TypeA {
pub opt: …
```
> Add recursive schema option support 

- project-example/schema/example.schema
- project-example/src/generated.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/src/worker/entity.rs
- spatialos-sdk/src/worker/schema/owned.rs
This PR adds support for both generated enums and entity keys in schema maps.
For enums, just derive the traits required in the generated code.
For schema entities:
- Use `BTreeMap` instead of `HashMap` in the `Entity` type.
- Impl `PartialEq`, `Eq`, `PartialOrd`, `Ord` for `Owned<T>` using the `NonNull` implementations (the ptr address)
- We can now derive the required traits on `Entity`! 
This solves _some_ of the problems described in #153
> Support enums & schema entity as keys in schema maps

- spatialos-sdk/src/worker/schema/primitives.rs
Added defaults when deserialising primitive types, to match pbio as seen in https://github.com/improbable/protobuf-interop/blob/4f1363cf2522dc97eba7b669c00731a88b2de9e4/src/pbio.cc#L367
For some reason, default values are not present when sent from spatial, leading to errors when deseralising things such as Position(0,0,0)
> Primitive schema type defaults

- spatialos-sdk/Cargo.toml
- spatialos-sdk/resources/bad_bundle
- spatialos-sdk/resources/good_bundle
- spatialos-sdk/src/worker/schema.rs
- spatialos-sdk/src/worker/schema/bundle.rs
- spatialos-sdk/src/worker/schema/generic_data.rs
The last bit of the 14.1.0 upgrade that I ommitted in #157. This PR adds support for schema bundles. 
There are a number of tests except for the command conversions. I used the schema standard library to generate the binary bundle representations which doesn't have any interesting commands (only empty ones).
In a follow up PR, I'm going to add an option to generate a binary bundle as well as the JSON one in `cargo spatial codegen` and use that to generate more interesting bundles. This is just to keep the PR a bit smaller (its already fairly large).
> Add schema bundles

- .github/workflows/premerge.yml
- .idea/runConfigurations/Download_SDK.xml
- README.md
- project-example/src/generated.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk-code-generator/src/generator.rs
- test-suite/Spatial.toml
Opening this PR to track the various issues left in the code generator (as found by the exhaustive schema package).
- Seems related to the constraint that the key in the map must implement `Ord` - https://github.com/jamiebrynes7/spatialos-sdk-rs/blob/tests/exhaustive-schema/spatialos-sdk/src/worker/schema/collections.rs#L151
- Things like generated enums, generated types, schema entity, don't implement `Ord`.
> Use exhaustive schema package

- .github/workflows/premerge.yml
- project-example/src/generated.rs
- project-example/src/main.rs
- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/src/worker/commands.rs
- spatialos-sdk/src/worker/component.rs
- spatialos-sdk/src/worker/connection.rs
- spatialos-sdk/src/worker/op.rs
- spatialos-sdk/src/worker/schema.rs
Following on from @randomPoison's ideas in #121 and examples in various previous PRs, this PR splits out  the `CommandResponse` and `CommandRequest` traits from the `Component` trait. 
It also restructures the traits somewhat such that there is a `Commands` trait which is only implemented if there any commands associated with that component. This cuts down on unnecessary generated code and models the domain (schema) a bit more accurately.
There are a number of associated changes in this PR:
- Refactored `StatusCode` in command response ops to just be a plain old `Result<T, E>`.
- Removed some unused types/methods
- Moved command related things into the `commands.rs` file
> Command traits

- .idea/spatialos-sdk-rs.iml
- Cargo.toml
- cargo-spatial-package-downloader/Cargo.toml
- cargo-spatial-package-downloader/src/lib.rs
- cargo-spatial/Cargo.toml
- cargo-spatial/src/download.rs
- spatialos-sdk-sys/Cargo.toml
- spatialos-sdk-sys/build.rs
This PR builds on the ideas in #167 
If `SPATIAL_LIB_DIR` is not set, the `spatialos-sdk-sys` package will download the packages for the target OS into its `OUT_DIR` location. 
In order to not bloat the `spatialos-sdk-sys` build dependencies, I've pulled out the package downloading code into its own little library.
> Download `spatialos-sdk-sys` packages at runtime

- cargo-spatial/src/config.rs
- cargo-spatial/src/local.rs
At some point in the past, supplying a runtime version to `spatial local launch` became mandatory. This then broke `cargo spatial local launch`. This PR resolves this issue.
> Support pinned runtime version

- spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
- spatialos-sdk/src/worker/schema/float_ord.rs
Allows you to write something like: 
```rust
improbable::Coordinates {
x: 100.0.into(),
..Default::default(),
}
```
or similar with any generated components/types (it seems update already had this implemented).
> Derive `Default` for generated components and types
