jamiebrynes7/spatialos-sdk-rs

spatialos-sdk/examples/project-example/main.rs
spatialos-sdk/examples/project-example/spatial-os/world.json
spatialos-sdk/src/worker/core/connection.rs
spatialos-sdk/src/worker/core/metrics.rs
spatialos-sdk/src/worker/core/mod.rs

This PR fleshes out the remaining APIs on the connection except for those relating to components and commands.
This should check off most of the elements in #15 
Left to implement in this PR:

Flesh Out Connection

---

spatialos-sdk/examples/project-example/setup.sh

Fix Setup Script

---

.travis.yml
README.md

Some little bits here and there

Misc Changes

---

.travis.yml
spatialos-sdk-sys/Cargo.toml
spatialos-sdk-tools/Cargo.toml
spatialos-sdk-tools/src/download_sdk/main.rs
spatialos-sdk/Cargo.toml
spatialos-sdk/examples/project-example/lib/connection_handler.rs
spatialos-sdk/examples/project-example/main.rs
spatialos-sdk/src/bin/generate_snapshot.rs
spatialos-sdk/src/worker/commands.rs
spatialos-sdk/src/worker/component.rs
spatialos-sdk/src/worker/connection.rs
spatialos-sdk/src/worker/locator.rs
spatialos-sdk/src/worker/metrics.rs
spatialos-sdk/src/worker/mod.rs
spatialos-sdk/src/worker/op.rs
spatialos-sdk/src/worker/parameters.rs
spatialos-sdk/src/worker/query.rs
spatialos-sdk/src/worker/snapshot.rs

See title. Some drivebys to get rid of warnings on build.

Upgrade to Rust 2018 Edition

---

ci/install.sh
ci/lint.sh
spatialos-sdk-sys/src/lib.rs
spatialos-sdk-tools/src/download_sdk/main.rs
spatialos-sdk/examples/project-example/lib/connection_handler.rs
spatialos-sdk/src/bin/generate_snapshot.rs
spatialos-sdk/src/worker/connection.rs
spatialos-sdk/src/worker/locator.rs
spatialos-sdk/src/worker/metrics.rs
spatialos-sdk/src/worker/mod.rs
spatialos-sdk/src/worker/op.rs
spatialos-sdk/src/worker/parameters.rs
spatialos-sdk/src/worker/query.rs
spatialos-sdk/src/worker/snapshot.rs

* Fixed all clippy warnings.
* Added clippy to linting step in CI

Add Clippy to lint step

---

spatialos-sdk/src/worker/parameters.rs

Add nice Rust interface for KCP connection introduced between `13.3` and `13.5`

Add KCP Connection Type

---

spatialos-sdk-sys/Cargo.toml

Bump sys crate version

---

spatialos-sdk/src/worker/connection.rs

Addition of `get_connection_status_code` and `get_connection_status_detail`. Deprecated `is_connected`

13.5.1 Upgrade - Connection Status changes

---

project-example/spatialos.json
project-example/src/connection_handler.rs
project-example/src/opt.rs
project-example/world.json
spatialos-sdk/src/worker/alpha.rs
spatialos-sdk/src/worker/alpha_locator.rs
spatialos-sdk/src/worker/connection.rs
spatialos-sdk/src/worker/internal/utils.rs
spatialos-sdk/src/worker/locator.rs
spatialos-sdk/src/worker/mod.rs
spatialos-sdk/src/worker/parameters.rs

Connect to cloud deployments with the alpha locator / development auth connection flow.
Fixes #24

Alpha Locator / Development Authentication connection flow

---

spatialos-sdk/src/worker/connection.rs

Fix crash on connection failure

---

README.md
spatialos-sdk/src/worker/connection.rs
spatialos-sdk/src/worker/query.rs

Make Clippy happy + update README

Rust 1.34 Upgrade

---

project-example/schema/example.schema
project-example/src/main.rs
spatialos-sdk-code-generator/src/generator.rs

Fixes #72 
Small fix to enable schema imports. Source of the bug was we were calculating the type of the field using the current package rather than the owner of that type. 
Updated example project accordingly

Fix schema imports

---

project-example/schema/example.schema
project-example/src/generated.rs
spatialos-sdk/src/worker/internal/schema.rs

Added a test case for it. One day I'll pull in the exhaustive schema test package.

Actually fix entity id this time

---

.idea/runConfigurations/Check.xml
spatialos-sdk/src/worker/component.rs
spatialos-sdk/src/worker/op.rs

Simple case of just swapping a few fields/structs to `pub` 😄

Expose Schema API 

---

.github/actions-rs/grcov.yml
.github/workflows/premerge.yml

Thanks to https://github.com/actions-rs/grcov this is pretty simple to setup. Arbitrarily chosen to publish to https://codecov.io
Nothing is gated on these metrics, just interesting to see them :)

Add code coverage build job

---

.github/workflows/premerge.yml
codecov.yml

Added a very minimal codecov configuration which shouldn't fail PRs any more regarding code coverage, but it should still be reported.

Add codecov config file

---

codecov.yml

Really just want this for informational purposes

Make patch reporting never fail

---

project-example/src/generated.rs
spatialos-sdk-code-generator/src/generated_code_mod.tt.rs
spatialos-sdk-code-generator/src/generator.rs
spatialos-sdk/src/worker/component.rs
spatialos-sdk/src/worker/schema/component_update.rs

Supersedes #115. Just decided to re-implement it since the backing code had changed a bit inbetween. 
This PR adds event support into the code generated types.

Events implementation

---

.github/workflows/premerge.yml
.idea/runConfigurations/Download_SDK.xml
README.md
cargo-spatial/src/config.rs
project-example/src/main.rs
spatialos-sdk-sys/Cargo.toml
spatialos-sdk-sys/src/worker.rs
spatialos-sdk/src/worker/connection.rs
spatialos-sdk/src/worker/logging.rs
spatialos-sdk/src/worker/mod.rs
spatialos-sdk/src/worker/parameters.rs

- Update Worker SDK to 14.8.0
- Removed deprecated APIs where possible
- Change Locator port from 444 to 443 (missed in #173)

Update to Worker SDK 14.8.0

---

project-example/src/generated.rs
spatialos-sdk/src/worker/logging.rs
spatialos-sdk/src/worker/parameters.rs

In most of these we had a `default()` method, but not an actual `Default` trait impl. This PR resolves this.

Implement `Default` for all the parameters
